export const COMMON = {
  SET_LOADING: "SET_LOADING",
  UNSET_LOADING: "UNSET_LOADING",
  SET_ORG_NAME: "SET_ORG_NAME",
  SET_ORG_LOGO: "SET_ORG_LOGO",
  SET_MOBILE: "SET_MOBILE",
};

export const LOGIN = {
  GET_LOGIN_DATA: "GET_LOGIN_DATA",
  GET_USER_NAME: "GET_USER_NAME",
  GET_JOIN_LINK: "GET_JOIN_LINK",
  SET_LOGGED_IN: "SET_LOGGED_IN",
  SET_PASSWORD: "SET_PASSWORD",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
};

export const DEVICE = {
  GET_DEVICES: "GET_DEVICES",
  SET_DEVICES: "SET_DEVICES",
  GET_CAMERA_ID: "GET_CAMERA_ID",
  GET_MICROPHONE_ID: "GET_MICROPHONE_ID",
  GET_SPEAKER_ID: "GET_SPEAKER_ID",
  SET_CAMERA_ID: "SET_CAMERA_ID",
  SET_MICROPHONE_ID: "SET_MICROPHONE_ID",
  SET_SPEAKER_ID: "SET_SPEAKER_ID",
  SET_SETUP_COMPLETED: "SET_SETUP_COMPLETED",
  UNSET_SETUP_COMPLETED: "UNSET_SETUP_COMPLETED",
  TOGGLE_CAMERA_ON: "TOGGLE_CAMERA_ON",
  TOGGLE_MIC_ON:"TOGGLE_MIC_ON",
};
