name: Build and deploy Node.js app to Azure Web App - sitename

on:
  push:
    branches: [ "az/deployment" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: confera
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  REACT_APP_SERVER_URL: 'https://confera-server.azurewebsites.net/'
  REACT_APP_COMPANY_NAME: 'Confera'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
            node-version: '18.x'
            
      - name: npm install, build
        run: |
          npm install
          CI=false npm run build --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: $

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZ_CONFERA_PUBLISH_PROFILE  }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}